asset_id = ""
num_input_notes = ""
input_note_1_index = ""
input_note_2_index = ""
input_note_1_path = []
input_note_2_path = []
input_note_1 = []
input_note_2 = []
output_note_1 = []
output_note_2 = []
account_note_witness = []
account_private_key = ""
alias_hash = ""
account_required = ""
account_note_index = ""
account_note_path = []
signing_pk = []
signature = []
proof_id = ""
output_note_commitment_1 = ""
output_note_commitment_2 = ""
public_value = ""
public_owner = ""
tx_fee = ""
tx_fee_asset_id = ""
bridge_call_data = ""
defi_deposit_value = ""
defi_root = ""
backward_link = ""
allow_chain = ""
tree_root = ""