tree_root = ""
account_public_key = []
new_account_public_key = []
signing_public_key = []
signature = []
new_signing_public_key_1 = []
new_signing_public_key_2 = []
alias_hash = ""
account_nonce = ""
create = ""
migrate = ""
account_note_index = []
account_note_path = []
note_1 = []
note_2 = []
return = []